### ISSUE TITLE
Unclear format for External Validate files

### ISSUE THREAD

**Issue by brycerowland** [biostat0903/DBSLMM#11]
Hi Sheng, 

Could you please clarify the format for the external summary statistics files? There is no clear guidance in the External Validate section of the DBSLMM manual. I assume that the columns are ID, effect allele, allele frequency, and the 4th column is either effect size or z statistic. Thanks!

Best,
Bryce

**Comment by brycerowland** [comment]
Hi Sheng, 

Can you please advise? 

Best,
Bryce

**Comment by biostat0903** [comment]
Hi Bryce , 
Sorry for the late response. We have updated the new version for `external` function. 
You can try to use it. If there is any problem, please feel free to ask me. 
I will response you as soon as possible. 
Best, 
Sheng
