### ISSUE TITLE
readExt function  erroneously accesses memory

### ISSUE THREAD

**Issue by brycerowland** [biostat0903/DBSLMM#12]
Hi Sheng, 

There is no test data provided for the `validate` function on the GitHub as suggested on the Manual, so maybe I'm missing something here that would be caught in the test case. My apologies if so. 

It seems that the `readExt` function in `dtpr.cpp` is erroneously trying to access data from the `snp_summ` variable. The line `summs.a1 = snp_summ[1];` results in a segmentation fault because snp_summ only has information in `snp_summ[0]`, which outputs the input line for the external validation files. For my data, it fails on the first line. Could you please make sure the validate code is up to date or provide a working example? 

Best,
Bryce

**Comment by biostat0903** [comment]
Hi Bryce, 
The input of `validate` is the output of `dbslmm`. You can try it. 
Best, 
Sheng

**Comment by brycerowland** [comment]
Hi Sheng, 
Thanks for your quick response. Please see my comment about the Seg Fault error in the readExt function. I was attempting to run validate on the output of DBSLMM, but could not get it to work. The comment on the test data was in hopes of having a workable example that you and/or the other developers have posted that definitely runs with the `validate` software as presented. 

Best,
Bryce

**Comment by brycerowland** [comment]
Hi Sheng,

Can you please advise regarding the bug mentioned above in the validate software, or let me know how I can provide a more reproducible example? 

Best,
Bryce

**Comment by biostat0903** [comment]
Hi, 
We have updated the external function. 
Please try to use it. Thanks !

Best, 
Sheng
