### ISSUE TITLE
LD block information on hg38

### ISSUE THREAD

**Issue by rujinwang** [biostat0903/DBSLMM#13]
Dear Sheng, 
Thanks for developing DBSLMM. I have a question regarding the LD block information. The 1703 blocks for the whole genome are built upon hg19. I am wondering how can I run DBSLMM if the genome build of both summary statistics and genotypes are hg38. 
I tried liftOver tools on the LD block information [here](https://bitbucket.org/nygcresearch/ldetect-data/src/master/EUR/), yielding 1625 hg38 LD blocks. However, DBSLMM reported errors: "Segmentation fault (core dumped)" and failed to fit the model using post-liftOver LD block information. 
Is DBSLMM internally only built upon hg19? Or, do you have any suggestions or comments if summary statistics and genotypes are from genomic build hg38? 

Thanks for your help. 

Best regards, 
Rujin

**Comment by biostat0903** [comment]
Hi Rujin, 
Thanks for your kindly attention to DBSLMM. Please delete the first line of the block information. 
The file is as following:
````bash
chr22	16050408	17674295
chr22	17674295	18296088
chr22	18296088	19912358
chr22	19912358	22357325
chr22	22357325	23712647
chr22	23712647	24984204
chr22	24984204	26791628
chr22	26791628	27834752
chr22	27834752	29651799
chr22	29651799	31439918
chr22	31439918	32664986
chr22	32664986	34494914
chr22	34494914	35530985
chr22	35530985	37570269
chr22	37570269	39307894
chr22	39307894	40545797
chr22	40545797	42690818
chr22	42690818	43714200
chr22	43714200	44995308
chr22	44995308	46470495
chr22	46470495	47596318
chr22	47596318	48903703
chr22	48903703	49824534
chr22	49824534	51243298
````
Best, 
Sheng

**Comment by biostat0903** [comment]
Is everything ok？

**Comment by LuQiao-spec** [comment]
Hi Sheng,

I have the same question with Rujin. Do you have hg38 LD blocks? Or should I liftover it from hg19 to hg38? 

Thanks,
Emma

**Comment by biostat0903** [comment]
Hi Qiao, 
Thanks for your consideration for DBSLMM. The block informaiton is hg19. 
We refer to: https://bitbucket.org/nygcresearch/ldetect-data/src/master/.


Best,
Sheng


发件人：Lu Qiao ***@***.***>
发送日期：2023-06-10 03:03:24
收件人：biostat0903/DBSLMM ***@***.***>
抄送人：Sheng Yang ***@***.***>,State change ***@***.***>
主题：Re: [biostat0903/DBSLMM] LD block information on hg38 (#13)

Hi Sheng,
I have the same question with Rujin. Do you have hg38 LD blocks? Or should I liftover it from hg19 to hg38?
Thanks,
 Emma
