### ISSUE TITLE
File path error in DBSLMM.R

### ISSUE THREAD

**Issue by MapleHe** [biostat0903/DBSLMM#14]
Hi Sheng Yang, thank you for your excellent tool.

In the latest version (`commit d1b71fa`) of master branch, the `DBSLMM.R` script in `software` folder will raise several errors like "Failed to open xxxxx.txt".

I inserted extra `"/"` mark to all the `paste0()` function right after `opt$outPath` var, then everything goes well.

**Comment by biostat0903** [comment]
Hi, 
Thanks for your attention to our software. You can also add extra "/" in the parameter "outPath". 
I hope DBSLMM can help you to perform GWAS prediction. Recently, I also find it works well in cross-ancestry prediction. If you need to do some analysis, you can try to use it. I will update the across-ancestry code as soon as possible. 
Thanks for you attention again
Best, 
Sheng

**Comment by MapleHe** [comment]
Thank you for your tip. 

To me a beginner,  the tool's usage can be more easy-to-understand than many other tools.

BTW, is it possible to support the plink-format (or simplified) input file ?

As I found  in the [source]( https://github.com/biostat0903/DBSLMM/blob/5b71d9542939a255d0277cf6c64bcf44f840d198/scr/dtpr.cpp#L162), the indispensible columns (headers) of the GWAS summary statistics file are (in PLINK format) CHR, SNP, BP(ps in GEMMA output), A1, A2, MAF. Right ?

It seems that the current version requires fixed GEMMA format.

Looking forward to your update !

Best wishes !

**Comment by biostat0903** [comment]
Hi, 
For DBSLMM, we should use the information of MAF, and allele information. We recommend you to use GEMMA. 
The code is as follows: 
````bash
gemma=/your/path/gemma
bfile=/your/path/bfile
col=/the/col/of/fam/file
summ=/the/output/of/GEMMA
${gemma} -bfile ${bfile} -notsnp -lm 1 -n ${col} -o ${summ}
````
Best,
Sheng

**Comment by MapleHe** [comment]
Thank you for your patience ! :)
