### ISSUE TITLE
How to tune the model

### ISSUE THREAD

**Issue by ChongWu-Biostat** [biostat0903/DBSLMM#15]
I found the following codes do not work:

for pv in 1e-05 1e-06 1e-07 1e-08
do
for r2 in 0.05 0.1 0.15 0.2 0.25
do
Rscript ${DBSLMM} --summary ${summf}${chr}.assoc.txt --outPath ${outPath} --plink ${plink} --dbslmm ${dbslmm} --ref ${ref}${chr} --pv ${pv} --r2 ${r2} --mafMax 1 --n ${n} --nsnp ${m} --type t --block ${blockf}${chr}.bed --h2 ${herit}

This is because the current version does not support pv and r2 parameters. Can we tune the model or the current version does not require tuning?

**Comment by biostat0903** [comment]
Hi Chong, 
Thanks for your continuous attention to `DBSLMM`. Now, we have updated it to v0.2. This version will tune the heritability. I will update the manual of it soon. 
Thanks again! 
Best, 
Sheng

**Comment by ChongWu-Biostat** [comment]
Hi Sheng,

Thank you. I am looking forward to that.

**Comment by biostat0903** [comment]
Hi Chong, 
The new manual is ok now! Please try to use it. 
Best,
Sheng

**Comment by biostat0903** [comment]
Hi Chong, 
Is there any problem of the DBSLMM？
Best, 
Sheng

**Comment by ChongWu-Biostat** [comment]
Hi Sheng,

I found that for some chromosomes, I am unable to get the results. For some chromosomes, it works perfectly. Any suggestions?

Thanks,
Chong

**Comment by biostat0903** [comment]
Hi Chong, 
Thanks for your consideration. Would you like to tell me the error? I would like to know the error is the code or the `dbslmm.txt` file? Thanks again!

Best, 
Sheng

**Comment by ChongWu-Biostat** [comment]
The error I am experiencing is this. It occurs after the DBSLMM attempts to fit all 3 h2f levels we assigned

> tmp = fread( paste(out_dir,"summary_gemma_chr",chr.id<http://chr.id>,"_h2f",0.8,".dbslmm.txt",sep=""))
Error in fread(paste(out_dir, "summary_gemma_chr", chr.id<http://chr.id>, "_h2f", 0.8,  :
  File '/gpfs/research/chongwu/austinking/CVD/BenchmarkMethods/DBSLMM/summary_gemma_chr11_h2f0.8.dbslmm.txt' does not exist or is non-readable. getwd()=='/gpfs/research/cho$
Execution halted

The code for that section (the h2f=0.8) looks like this:

Last login: Thu Feb 11 01:36:54 on console
(base) wc-dhcp84d086:~ Austin$ ssh ak16u@hpc-login.rcc.fsu.edu<mailto:ak16u@hpc-login.rcc.fsu.edu>
ak16u@hpc-login.rcc.fsu.edu<mailto:ak16u@hpc-login.rcc.fsu.edu>'s password:
Last login: Tue Feb  9 09:40:53 2021 from 10.136.84.86

Fitting model...
>
> h2f = 0.8
> command = paste("Rscript ",DBSLMMR," --summary ",inputfile," --outPath ",out_dir," --plink ",plink," --dbslmm ",dbslmm," --ref ",ld.ref," --n ",nsample," --nsnp ",nsnp," $
>
> system(command)
Acccept Options:
--summary:   /gpfs/research/chongwu/austinking/CVD/BenchmarkMethods/DBSLMM/summary_gemma_chr11.assoc.txt
--plink:     /gpfs/research/chongwu/shared/software/plink
--dbslmm:    /gpfs/research/chongwu/shared/software/DBSLMM/software/dbslmm
--ref:       /gpfs/research/chongwu/shared/1000Genomes/1000G.EUR.ALLSNP.QC.CHR11
--block:     /gpfs/research/chongwu/shared/LDetect_LD_regions/EUR/fourier_ls-chr11.bed
--outPath:   /gpfs/research/chongwu/austinking/CVD/BenchmarkMethods/DBSLMM/
--n:         184305
--nsnp:      6242742
--h2:        0.0474
--h2f:       0.8
--type:      Tune
--mafMax:    0.2

--thread:    5

Using , 3 SNPs are regarded as fixed effect.
Clumping time:  3.677 s.
Options:
-s: /gpfs/research/chongwu/austinking/CVD/BenchmarkMethods/DBSLMM/s_summary_gemma_chr11_h2f0.8.txt
-l: /gpfs/research/chongwu/austinking/CVD/BenchmarkMethods/DBSLMM/l_summary_gemma_chr11_h2f0.8.txt
-r: /gpfs/research/chongwu/shared/1000Genomes/1000G.EUR.ALLSNP.QC.CHR11
-nsnp:   6242742
-n: 184305
-mafMax: 0.2
-b: /gpfs/research/chongwu/shared/LDetect_LD_regions/EUR/fourier_ls-chr11.bed
-h: 0.03792
-t: 5
-eff:    /gpfs/research/chongwu/austinking/CVD/BenchmarkMethods/DBSLMM/summary_gemma_chr11_h2f0.8.dbslmm
Reading PLINK FAM file from [/gpfs/research/chongwu/shared/1000Genomes/1000G.EUR.ALLSNP.QC.CHR11.fam]
503 individuals to be included from reference FAM file.
Reading PLINK BIM file from [/gpfs/research/chongwu/shared/1000Genomes/1000G.EUR.ALLSNP.QC.CHR11.bim]
Calculating MAF of reference panel ...
477712 SNPs to be included from reference BIM file.
Reading summary data of small effect SNPs from [/gpfs/research/chongwu/austinking/CVD/BenchmarkMethods/DBSLMM/s_summary_gemma_chr11_h2f0.8.txt]
Number of allele discrepency: 289460
Number of maf discrepency:    339
After filtering, 24962 small effect SNPs are selected.
Reading summary data of large effect SNPs from [/gpfs/research/chongwu/austinking/CVD/BenchmarkMethods/DBSLMM/l_summary_gemma_chr11_h2f0.8.txt]
Number of allele discrepency: 3
Number of maf discrepency:    0
After filtering, 0 large effect SNPs are selected.
Fitting model...
>
>

The code stops running once it can't find the h2f0.8.dblsmm.txt file, but I think the same error would occur at the 1 and 1.2 levels. Basically what I have gathered from this is that it cases where 0 large effect SNPs are selected, the model won't be fit and it won't create the file properly. This seems to happen when all 3 h2f levels have 0 large effect SNPs. However, it cases where at least 1 of the levels has a large effect SNP then the code runs to completion.
--
Chong Wu
Assistant Professor
Department of Statistics
Florida State University





On Feb 10, 2021, at 7:14 AM, Sheng Yang <notifications@github.com<mailto:notifications@github.com>> wrote:



Hi Chong,
Thanks for your consideration. Would you like to tell me the error? I would like to know the error is the code or the dbslmm.txt file? Thanks again!

Best,
Sheng

**Comment by biostat0903** [comment]
Hi Chong, 
I will fix the bug in tomorrow. Sorry for the late feedback. 
Best, 
Sheng

**Comment by biostat0903** [comment]
Hi Chong, 
Sorry for the late response. I have update the file `dbslmm.cpp`, `dbslmm.hpp`, `dbslmmfit.cpp` and `dbslmm.hpp`. I do not sure whether you compile the `dbslmm` on your cluster or using the static version. I also update the static version `dbslmm` . Thanks for your attention to DBSLMM. 
Best, 
Sheng

**Comment by ChongWu-Biostat** [comment]
Thank you. I will try and let you know if it works or not.

Thanks,
Chong
--
Chong Wu
Assistant Professor
Department of Statistics
Florida State University





On Feb 17, 2021, at 10:07 AM, Sheng Yang <notifications@github.com<mailto:notifications@github.com>> wrote:



Hi Chong,
Sorry for the late response. I have update the file dbslmm.cpp, dbslmm.hpp, dbslmmfit.cpp and dbslmm.hpp. I do not sure whether you compile the dbslmm on your cluster or using the static version. I also update the static version dbslmm . Thanks for your attention to DBSLMM.
Best,
Sheng

**Comment by biostat0903** [comment]
Hi Chong, 
Thanks for your attention! I have updated the file and fix the bug. Unfortunately, the new version of `dbslmm` file is too large to share on github website. I upload it to google drive, and the address is https://drive.google.com/file/d/1TRqPozXtenDW9buQgzFQ2KSxxWhl7dNn/view?usp=sharing. If you need the static version, you can download it. If there are any problem, you can contact to me. Thanks again!
Best, 
Sheng
