### ISSUE TITLE
no LD blocks for chromosome X?

### ISSUE THREAD

**Issue by kkonoo** [biostat0903/DBSLMM#22]
Hi, there
I'm using your great software, DBSLMM now.
I have a question about chrX.
Isn't there any LD block information for chromosome X?
Can't I use this program for chromosome X?

Best,
E.H.

**Comment by kkonoo** [comment]
Sorry.
Oh, there is makeld.R !!

**Comment by biostat0903** [comment]
Hi, 
Sorry for the late reply. I think the block file is without sex chromosome. So the DBSLMM can not fit the X chromosome. 
Thanks for your attention to DBSLMM.
Best, 
Sheng
