### ISSUE TITLE
Which column is the scaled effects, the third? the fourth?

### ISSUE THREAD

**Issue by kkonoo** [biostat0903/DBSLMM#23]
Hi, there!
The third column of the output format is scaled effect sizes as written in your manual.rmd.
![image](https://user-images.githubusercontent.com/41933720/136877986-ffa6a792-19ef-4360-80c7-22cc0fd0c7d9.png)

However, according to your script, you seem to calculate PRS with the fourth column of DBSLMM output as follows.
![image](https://user-images.githubusercontent.com/41933720/136878009-f61aab86-fe1c-4df8-8599-d56b77503d24.png)

Which is correct?

**Comment by biostat0903** [comment]
Hi,
Sorry for the error. I update the manual in this page: https://github.com/biostat0903/DBSLMM. 
You can follow it. If there is any problem, you can ask me. 
Thanks for your attention to DBSLMM. 
Best, 
Sheng

**Comment by kkonoo** [comment]
Thank you for your fast reply.
And I have another question.
You say that the fourth column in the output file is non-scaled effect size.
What does it mean?
At first, I thought 'non-scaled' is the same with the effect size of the input summary file, but it was different from the ones in the input.
How was the fourth column calculated?

Best,
E.H.

**Comment by biostat0903** [comment]
Hi, 
Thanks again for your attention to DBSLMM. Both third and fourth column is estimated from DBSLMM, that is, the effect size of mixed model. The third column is the scaled effect, and fourth column is non-scaled. We use MAF to transfer scaled size to non-scaled size. 
Best, 
Sheng

**Comment by kkonoo** [comment]
Oh, I see.
Thank you for the reply!

Best,
E.H.
