### ISSUE TITLE
LD block data for SAS and AMR

### ISSUE THREAD

**Issue by opain** [biostat0903/DBSLMM#26]
Hello,

You provide LD block data for EUR, EAS and AFR populations. However, LD block data is not available for SAS and AMR populations (the other 1KG phase 3 super populations). Do you have advice on how to apply DBSLMM to GWAS summary statistics from these populations?

Many thanks,

Ollie

**Comment by biostat0903** [comment]
Hi Oliver, 
Thanks for your consideration of DBSLMM again. In the version, we cannot support the SAS and AMR. 


Best,
Sheng 


发件人：Oliver Pain ***@***.***>
发送日期：2024-01-08 18:02:15
收件人：biostat0903/DBSLMM ***@***.***>
抄送人：Subscribed ***@***.***>
主题：[biostat0903/DBSLMM] LD block data for SAS and AMR (Issue #26)

Hello,
You provide LD block data for EUR, EAS and AFR populations. However, LD block data is not available for SAS and AMR populations (the other 1KG phase 3 super populations). Do you have advice on how to apply DBSLMM to GWAS summary statistics from these populations?
Many thanks,
Ollie

**Comment by opain** [comment]
OK. Thank you for the reply.
