### ISSUE TITLE
C++ library dependencies

### ISSUE THREAD

**Issue by hmkweon** [biostat0903/DBSLMM#8]
Hello,

Thanks for the great software. But, I actually had a lot of difficulty getting it to work. The issue was its dependency on Armadillo library. I installed the library myself and It took me a while to get it working. It would be helpful to provide a guide about this. Perhaps, even better will be to build your software with RcppArmadillo and runs everything entirely within R instead of wrapping it.

**Comment by biostat0903** [comment]
Hi, 
Thanks for your attention. I have compiled a static version of dbslmm and upload to github today. The dbslmm is not RCpp, rather than the C/C++ executable file.  If there is any problem for dbslmm, please show me the error. 
Best, 
Sheng
